import { Outfit } from "next/font/google";
// import React,{useEffect } from "react";
import "./globals.css";
import Header from "./_components/Header";
import { Navbar } from "./_components/Hero2";
import Footer from "./_components/Footer";
import WatsonAssistantChat from "./_components/WatsonAssistantChat";
import NextAuthSessionProvider from "./provider";
import { Toaster } from "@/components/ui/sonner";
import '@smastrom/react-rating/style.css';


const inter = Outfit({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};   
export default function RootLayout({ children }) {
  return ( 
    <> 
      <html lang="en">
        <body className={inter.className}>
          <NextAuthSessionProvider>
            <div className=" mx-6 md:mx-16">
              <Navbar/>                                          
              <WatsonAssistantChat />
              {children}      
              <Toaster />
              <Footer/>                                
            </div>                  
          </NextAuthSessionProvider>      
        </body>
      </html>                                      
    </>
  );
}
